### ISSUE TITLE
[Feature Request] Allow not only 'descending' sorting, but 'ascending' also

### ISSUE THREAD

**Issue by dein0s** [poeapp/poeapp#116]
Currently I couldn't find any way to revert sorting, which is kinda usefull in some cases (like sorting To Dust jewels by `reduced duration` or Abyssus by `increased damage taken` etc.)
Would be a nice QoL.

**Comment by poeapp** [comment]
I think the use case for this is incredibly limited and adds technical complexity and additional load on the search cluster.  For these edge cases, please just use a Mod Filter to filter out the unacceptable values.

**Comment by dein0s** [comment]
I'd say that cases where you want to sort/check the lowest value are not so limited. 
Also, I don't see any real tech difficulties/complexities to reverse the order and how this changes can increase the load on the search cluster (as far as I can assume that you do process the results on fe).
But... Whatever, thanks for your response anyway.

**Comment by poeapp** [comment]
All sort requests have to be sent back to the search cluster.  Think of it this way, you only see 50 results per page currently.  Sure, I could sort the 50 results on that page, but they won't be relevant to you as there could be 10,000 items that match your original search (for instance, all 50 helms on the first page could be 50% rolls).  So in order to overcome this issue, the request must be sent back to the search cluster in order to compute again (for both asc and desc).

Sort can be super useful but should not be used to "filter" out the results that you don't care about.  If you're concerned about a particular mod being within a threshold, please use a filter; this is why I have included all of the possible mods within the mod filter section.

[Example filter for Abyssus](https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4QALMaeWAOzxWhABoRaAzAewwg4GsUasAF4oAJhjaIsWAHJgAtkVIBBeAE80aRGgAEAUSEd5a1DoBCiaHg40UEZiHkdRaEgG1QTlyVAoAHgAOWLAAxrAQGADEAKQ6tCHQuGhiOgAKZBqhYFg6ACIK+Cg6EGD8NO4gDgAsAAwgALoAviwQagFK4DSiII1NQA)

**Comment by dein0s** [comment]
I definitely can differ 'filter' and 'sort' terms. And Abyssus was just a fast example off top of my head. I mostly use more sophisticated searches.
As the counterweight to your statement about "particular mod being within a threshold" - what's the point in sorting by mods at all then? If we can simply 'filter' out the results :)

Looks like I can't get your dev point on this. But, well, that's my problem then :D

**Comment by poeapp** [comment]
At the end of the day if there was a much larger use case for having both asc and desc sort for all mods, I would be more likely to implement it.  Right now, there are only a few mods that it makes sense to include.  There are over 4000 mods in game at this point in time, and of those 4000 maybe less than 1% of them make sense to be sorted in ascending order.  By adding the functionality, it could make the UX worse (click once to sort by desc, click again to sort by asc - or have two arrows next to each mod).  By doing that, it puts additional load on the backend cluster.

For such a small use case and the impact that it may have on overall load, it just isn't a priority to me at the moment.
