### ISSUE TITLE
[Bug?] Mods are not sorted when I start typing in the mod field

### ISSUE THREAD

**Issue by Xebtria** [poeapp/poeapp#138]
### Did you clear your browser cache before trying to reproduce?
- [x] Yes
Used incognito for testing
### Did you disable all browser extensions before trying to reproduce?
- [x] Yes
Used incognito for testing
### App Version
Current version is 2017-12-16T14:43:08.417Z

### Description
Mod "search" results when typing in the mods field are not sorted, it is very hard to find the mods I want sometimes. e.g. I want to search for "pseudo: total to all elemental resistances: >120" for a ring. I usually type "resistance".

### Expected outcome
poe.trade lists all common wanted mods in the first 7 hits, including the one I want.
![image](https://user-images.githubusercontent.com/8898076/34076637-6b54534c-e2ed-11e7-9627-97f379147faa.png)
pathofexile.com/trade lists all common wanted mods in the first 8 hits, also including the one I want
![image](https://user-images.githubusercontent.com/8898076/34076646-909480f0-e2ed-11e7-8950-db5863ea0b06.png)

### Actual outcome
poeapp.com, frankly, everything is a mess
![image](https://user-images.githubusercontent.com/8898076/34076648-ba27191e-e2ed-11e7-93bc-e72b4f51412f.png)

and to give an example how far I need to scroll down to find the one pseudo mod I want... well, see for yourself:
![image](https://user-images.githubusercontent.com/8898076/34076651-d3f4db7e-e2ed-11e7-8ade-7e5d34512e72.png)

### Steps to reproduce
see description

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE 11
- [ ] iOS Safari
- [x] Android Chrome

I only can check with these three (I don't have the others), and it happens on all of them

**Comment by poeapp** [comment]
poeapp actually works a bit differently than the other sites.  It uses a score-based, fuzzy search for the `mods` and `name` dropdowns.  In your case, you will want to use the search term `pseudo res`.  You can also use `max life` instead of `maximum life`, for example.

It takes your term, scores each hit, and sorts by high to low score.  In fact, [it even supports misspellings](https://imgur.com/a/U742V).

You can find more information about [fuzzy search terms here](https://www.reddit.com/r/pathofexile/comments/7dpd8y/qol_fuzzy_search_for_name_and_mods_on_poeappcom/).
