### ISSUE TITLE
Pseudo-duplicate modifier, "Next Area will contain up to # additional Monster imprisoned by Essences"

### ISSUE THREAD

**Issue by just-a-bird** [poeapp/poeapp#70]
The wording is technically different because "Monster" is singular, but it should be merged with `Next Area will contain up to # additional Monsters imprisoned by Essences`.

There is a similar issue of with the Echoes suffix (`Imprisoned Monsters in the next Area will have an additional Essence`).

**Comment by just-a-bird** [comment]
Looks like each of these modifiers also appear twice in the list.

**Comment by poeapp** [comment]
Unfortunately, this is due to the naming conventions that GGG uses, and I little control over this without writing some custom code that could eventually cause things to break down the road.

[Here are screenshots showcasing the two different mods existing on different items](http://imgur.com/a/iIxhV)

If you're looking for these specific mods, you should use these queries.  If one of them happens to go away in the future, the index and mods list will fix itself.

[monster(s) imprisoned](https://poeapp.com/#N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4Qc8wBjATxABoQB7AOy1maNJVggAsVo9EAFtGAEzQkA2qFESSoFAA8ADm0o8MAOWUQABAEFouPQHdYWLHsosIYdnsQq9ERnoDEesGLE9YLMCsAWRY0VGg9WGEVODQWFDE9eGo9AFE0NBRmSnRpZkRLOnzLAF0GZTVYDQhtXUNjMDMLKxtmOwcnFzdPb18If2ZAvRDmMIE0SOjY+MTktIysnMliKWKsIoKsEoBfBghqFU4QG0Q2oWgwZjxOKRAARno1nZ2gA)

[of echoes](https://poeapp.com/#N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4Qc8wBjATxABoQB7AOy1maNJVggAsVo9EAFtGAEzQkA2qFESSoFAA8ADm0o8MASWEq4aFijEACALIs0qaGmPtjfFMY5KIxgILRcxgO6wsWY14wADdHAGJjMDExHlgWMACAUTQ0FGZKdGlmRH86bP8AXQZlNVgNCG1dfUMTc2ZLARs7BydlVw8vX39AkMcwZkjo2PiklLSMkhhCAF8GCGoVThBKRkRmCCFofrxOKRAARnp8rALp06A)

**Comment by just-a-bird** [comment]
I know how to get around it, but you really should implement a mapping mechanism for cases like these. Both duplicate mods take the same number of parameters (one) so I don't see how it's prone to break unless GGG changes the wording of either of the mods, in which case, you'd simply need to update the mapping.

**Comment by poeapp** [comment]
The mappings are actually super flexible and resilient with very little code dependency.  If I introduce code there for this use case, we can't protect it from some future use case that may not need this change.  As the "legacy" items disappear in this instance, so will the searchable mods from the list.

**Comment by just-a-bird** [comment]
If it's only for this league, fair enough, it's not worth it. I suspect they aren't, though, so I guess it can be revisited in 3.0.

**Comment by poeapp** [comment]
I have a feeling that leaguestones will stick around, and we can revisit this later.  I would rather not create a dependency on this that could create rogue issues in the future that we would have to track down.  It's best to just create a preset for this that combines both for now.
